routes/web.php
        \Debugbar::disable();
    });

//    Route::post('/forgot_password', [App\Http\Controllers\V2\Auth\LoginController::class, 'forgot_password'])->name('v2.admin.forgot_password.store');
//    Route::get('/forgot_password', [App\Http\Controllers\V2\Auth\LoginController::class, 'get_forgot_password'])->name('v2.admin.forgot_password');
//    Route::get('/resetpass', [App\Http\Controllers\V2\Auth\LoginController::class, 'refresh_password'])->name('v2.admin.reset_password');
//    Route::post('/resetpass', [App\Http\Controllers\V2\Auth\LoginController::class, 'refresh_password_post']);

    Route::group(['prefix' => '/admin', 'middleware' => ['auth', 'auth.admin']], function () {
        Route::group(['middleware' => 'checkRole:1'], function () {
            Route::post('/logout', [App\Http\Controllers\V2\Auth\LoginController::class, 'logout'])->name('v2.admin.logout');

            Route::get('/client_login/{user}', [App\Http\Controllers\V2\AdminController::class, 'client_login'])->name('client_login');
            Route::resource('users', App\Http\Controllers\V2\UserController::class);
            Route::resource('roles', App\Http\Controllers\V2\RoleController::class);

            Route::resource('smstemplates', App\Http\Controllers\V2\SMSTemplateController::class);
            Route::delete('/deleteall_sms_tem', [\App\Http\Controllers\V2\SMSTemplateController::class, 'destroyAllSelections'])->name('deleteall_sms_tem');
            Route::put('/update/sms_temp/status/{smstemplate}', [\App\Http\Controllers\V2\SMSTemplateController::class, 'updateVisible'])->name('update.sms_temp');
            Route::get('/send/sms/clients', [\App\Http\Controllers\V2\SMSTemplateController::class, 'smsSendToClient'])->name('send.sms.admin');
            Route::post('/send/sms/clients', [\App\Http\Controllers\V2\SMSTemplateController::class, 'smsSendToClientPost'])->name('send.sms.admin.post');

            Route::resource('emailtemplates', App\Http\Controllers\V2\EmailTemplateController::class);
            Route::delete('/deleteall_email_tem', [\App\Http\Controllers\V2\EmailTemplateController::class, 'destroyAllSelections'])->name('deleteall_email_tem');
            Route::put('/update/email_temp/status/{emailtemplate}', [\App\Http\Controllers\V2\EmailTemplateController::class, 'updateVisible'])->name('update.email_temp');

            Route::delete('/adminus_destroyAllSelections', [\App\Http\Controllers\V2\AdminPanelUsersController::class, 'destroyAllSelections'])->name('adminus.deleteSelections');
            Route::resource('admin_panel_users', App\Http\Controllers\V2\AdminPanelUsersController::class);
            Route::delete('/roles_destroyAllSelections', [\App\Http\Controllers\V2\RoleController::class, 'destroyAllSelections'])->name('roles.deleteSelections');
            Route::resource('mektublar', App\Http\Controllers\V2\MektublarController::class);
            Route::delete('/mektub_destroyAllSelections', [\App\Http\Controllers\V2\MektublarController::class, 'destroyAllSelections'])->name('mektub.deleteSelections');
            Route::resource('coupons', App\Http\Controllers\V2\CouponController::class);
            Route::delete('/coupons_destroyAllSelections', [\App\Http\Controllers\V2\CouponController::class, 'destroyAllSelections'])->name('coupons.deleteSelections');

            Route::resource('category', \App\Http\Controllers\V2\CategoryController::class)->except('show');
            Route::delete('/categories_destroyAllSelections', [\App\Http\Controllers\V2\CategoryController::class, 'destroyAllSelections'])->name('category.deleteSelections');
            Route::put('/categories/update_category_visibility/{category}', [\App\Http\Controllers\V2\CategoryController::class, 'update_category_visibility'])->name('update_category_visibility');

        });
        Route::group(['middleware' => 'checkRole:1|4|3'], function () { //Kuryer
            Route::get('orders', [App\Http\Controllers\V2\OrderController::class, 'index'])->name('orders');
            Route::get('orders/{orderId}/{type}/showDetail', [App\Http\Controllers\V2\OrderController::class, 'showDetail'])->name('orders.showDetail');
            Route::post('orders/detail/update', [App\Http\Controllers\V2\OrderController::class, 'updateOrderDetailStatus'])->name('orders.updateOrderDetailStatus');
            Route::delete('orders/{detailId}/detail', [App\Http\Controllers\V2\OrderController::class, 'deleteOrderDetail'])->name('orders.deleteOrderDetail');
            Route::post('/orders/stock', [App\Http\Controllers\V2\OrderController::class, 'updateStock'])->name('orders.stock');
        });
        Route::group(['middleware' => 'checkRole:1|5'], function () { // Kontent
            Route::resource('banners', App\Http\Controllers\V2\BannerController::class);
            Route::put('/banner/update_banner_visibility/{banner}', [\App\Http\Controllers\V2\BannerController::class, 'update_banner_visibility'])->name('update_banner_visibility');
            Route::delete('/banner/delete/{banner}', [\App\Http\Controllers\V2\BannerController::class, 'destroy'])->name('delete_banner');
            Route::resource('brands', App\Http\Controllers\V2\BrandController::class);
            Route::delete('/stories_destroyAllSelections', [\App\Http\Controllers\V2\StoryController::class, 'destroyAllSelections'])->name('story.deleteSelections');
            Route::delete('/color_destroyAllSelections', [\App\Http\Controllers\V2\ColorController::class, 'destroyAllSelections'])->name('color.deleteSelections');
            Route::resource('stories', App\Http\Controllers\V2\StoryController::class);
            Route::resource('colors', App\Http\Controllers\V2\ColorController::class);
        });
        Route::group(['middleware' => 'checkRole:1|4|5'], function () { // Kontent ve ANbar
            Route::resource('products', App\Http\Controllers\V2\ProductController::class);
            Route::get('/product/{product_id}/changeStatus', [App\Http\Controllers\V2\ProductController::class, 'productsStatus'])->name('products.status');
            Route::post('/product/removeProductFromCombine', [App\Http\Controllers\V2\ProductController::class, 'removeProductFromCombine'])->name('products.removeProductFromCombine');
        });
        Route::group(['middleware' => 'checkRole:1|4'], function () {  //ANbar
            Route::resource('refler', App\Http\Controllers\V2\ReflerController::class);
            Route::delete('/refler_destroyAllSelections', [\App\Http\Controllers\V2\ReflerController::class, 'destroyAllSelections'])->name('refler.deleteSelections');
        });
        Route::group(['middleware' => 'checkRole:1'], function () {  //Statistics
            Route::get('statistics', [App\Http\Controllers\V2\StatisticsController::class, 'index'])->name('statistics.index');
            Route::get('statistics/{type}', [App\Http\Controllers\V2\StatisticsController::class, 'getData'])->name('statistics.getData');
        });
//        Route::get('dashboard', [App\Http\Controllers\V2\AdminController::class, 'dashboard'])->name('dashboard');
    });
});


// V1 Routes

//Route::redirect('/', '/login');
Route::get('', [HomeController::class, 'index'])->name('main');
Route::get('/login', [LoginController::class, 'index'])->name('admin.login');
Route::post('/login', [LoginController::class, 'login']);

Route::prefix('admin')->middleware(['auth', 'auth.admin'])->name('admin.')->group(function () {
    Route::get('/', [AdminController::class, 'products'])->name('dashboard');
    Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
    Route::post('/logout', [LoginController::class, 'logout']);

    Route::post('/file/{type}', [AdminController::class, 'uploadFile'])->name('file.upload');
    Route::delete('/file/{id}', [AdminController::class, 'deleteFile'])->name('file.delete');

    Route::get('api/products', [AdminController::class, 'productsList']);
    Route::get('api/users', [AdminController::class, 'usersList']);

    Route::get('/products', [AdminController::class, 'products'])->name('products');
    Route::get('/products/create', [AdminController::class, 'productsCreate'])->name('products.create');
    Route::post('/products/create', [AdminController::class, 'productsStore'])->name('products.store');
    Route::get('/products/{product_id}', [AdminController::class, 'productsEdit'])->name('products.edit');
    Route::put('/products/{product_id}', [AdminController::class, 'productsUpdate'])->name('products.update');
    Route::post('/products/{product_id}', [AdminController::class, 'productsStatus'])->name('products.status');
    Route::delete('/products/{product_id}', [AdminController::class, 'productsDelete'])->name('products.delete');

    Route::get('/orders', [AdminController::class, 'orders'])->name('orders');
    Route::post('/orders', [AdminController::class, 'ordersStatus'])->name('orders.status');
    Route::post('/orders/stock', [AdminController::class, 'updateStock'])->name('stock');
    Route::delete('/orders/{orderno}/{type}', [AdminController::class, 'ordersDelete']);
    Route::get('/api/orders', [AdminController::class, 'ordersList']);
    Route::get('/api/orders/{order}/{type}', [AdminController::class, 'ordersInfo']);

    Route::get('/banners', [BannerController::class, 'index'])->name('banners');
    Route::post('/banners', [BannerController::class, 'store'])->name('banners.store');
    Route::put('/banners', [BannerController::class, 'update'])->name('banners.update');
    Route::post('/banners/{banner_id}', [BannerController::class, 'status'])->name('banners.status');
    Route::delete('/banners/{banner_id}', [BannerController::class, 'destroy'])->name('banners.delete');

    Route::get('/thumb', [AdminController::class, 'addTuhumbnail']);
    Route::get('/resize/{type}/{down}/{up}', [AdminController::class, 'resize']);
    Route::get('/variations', [AdminController::class, 'variations']);

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function children()
    {
        return $this->hasMany(self::class, 'parent_id')->with(['children']);
    }

    public function products()
    {
        return $this->hasMany(Product::class)->where('products.confirmed', true)->limit(4);
    }

    public function children2()
    {
        return $this->hasMany(self::class, 'parent_id')->with(['children' => function ($query) {
            $query->select('id', 'parent_id', 'name');
        }]);
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use App\Traits\ApiResponser;
use Illuminate\Http\Request;

class CategoryController extends Controller
{
    use ApiResponser;

    function list(Request $request) {
        $categories = Category::where(['published' => true, 'parent_id' => 0])->with(['children'])->orderBy('rank', 'asc')->get();
        return $this->sendResponse($categories);
    }

    public function show(string $slug)
    {
        $product = '';
        return $this->sendResponse($product);
    }
}

app/Http/Controllers/V2/AdminController.php
<?php

namespace App\Http\Controllers\V2;

use App\Http\Controllers\Controller;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Support\Facades\Redirect;

class AdminController extends Controller
{
    private $pac = "Modabu Personal Access Client";

    public function dashboard()
    {
        return view('admin.v2.dashboard');
    }

    public function client_login(User $user)
    {
        $tokenResult = $user->createToken($this->pac);

        return Redirect::to('https://modabu.az/?token_client_access=' . $tokenResult->accessToken);
    }
}

app/Http/Controllers/V2/AdminPanelUsersController.php
<?php

namespace App\Http\Controllers\V2;

use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\RoleUser;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Pipeline\Pipeline;
use Illuminate\Support\Facades\Hash;

class AdminPanelUsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = User::query()->has('roles')
            ->orderBy('created_at', 'desc');

        if ($request->has('role')) {
            if ($request->role) {
                $users = User::query()->orderBy('created_at', 'desc');
            }
        }
        $user = $users->with('roles');

        $users = app(Pipeline::class)
            ->send($users)
            ->through([
                \App\QueryFilters\Name::class,
                \App\QueryFilters\Role::class,
            ])
            ->thenReturn()
            ->paginate(getPaginationLimit());

        $roles = Role::select([
            'id', 'title'
        ])->get();

        return view('admin.v2.adminpanel_users.index', compact('users', 'roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function store(\App\Http\Requests\V2\AdminPanelUserRequest $request, User $user, RoleUser $roleUser)
    {
        $data = $request->except('_token');
        $data['password'] = Hash::make($data['password']);
        $user->fill($data);
        $user->save();
        $roleUser->insert([
            'role_id' => $data['roles'],
            'user_id' => $user->id
        ]);
        return redirect(route('admin_panel_users.index'))->with('success', 'Əməliyyat uğurla Insert Oldu.');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param User $admin_panel_user
     * @return \Illuminate\Http\Response
     */
    public function update(\App\Http\Requests\V2\AdminPanelUserRequest $request, User $admin_panel_user)
    {
        $data = $request->except('_token');
        if ($data['password']) {
            $data['password'] = Hash::make($data['password']);
        } else {
            $data['password'] = $admin_panel_user->password;
        }
        if ($data['roles']) {
            RoleUser::where('user_id', $admin_panel_user->id)->update([
                'role_id' => $data['roles']
            ]);
        }
        if (!$data['phone']) {
            $data['phone'] = $admin_panel_user->phone;
        }
        $admin_panel_user->fill($data);
        $admin_panel_user->save();
        return redirect(route('admin_panel_users.index'))->with('success', 'Əməliyyat uğurla Update Oldu.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $admin_panel_user)
    {
        RoleUser::where('user_id', $admin_panel_user->id)->delete();
        User::where('id', $admin_panel_user)->delete();
        return response()->json(['message' => 'Silinme uğurla tamamlandı.'], 200);
    }

    public function destroyAllSelections(Request $request)
    {
        $request->validate(['keys' => 'present']);
        if ($request->keys) {
            $array = explode(',', $request->keys);
            RoleUser::whereIn('user_id', $array)->delete();
            User::whereIn('id', $array)->delete();
        }
        return response()->json(['message' => 'Əməliyyat uğurla tamamlandı.'], 200);
    }
}

app/Http/Controllers/V2/Api/ApiController.php
<?php

namespace App\Http\Controllers\V2\Api;

use App\Http\Controllers\Controller;
use App\Models\City;
use App\Traits\ApiResponser;
use Illuminate\Http\Request;

class ApiController extends Controller
{
    use ApiResponser;
    public function cities()
    {
        return $this->sendResponse(City::all(), '');
    }
}

app/Http/Controllers/V2/Api/User/OrderController.php
<?php

namespace App\Http\Controllers\V2\Api\User;

use App\Http\Controllers\Controller;
use App\Http\Requests\PayDirectlyRequest;
use App\Http\Resources\OrderCollection;
use App\Http\Resources\OrderResource;
use App\Models\Color;
use App\Models\Order;
use App\Models\OrderForm;
use App\Models\Product;
use App\Models\User;
use App\Models\Variation;
use App\Traits\ApiResponser;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\DB;

class OrderController extends Controller
{
    use ApiResponser;

    public function getOrders(Request $request)
    {
        $limit = 5;
        $user = User::find($request->user()->id);
        $orders = $user->orders()->orderBy('created_at', 'desc')->with(['detail'])->paginate($limit);
        return new OrderCollection($orders);
    }

    public function getOrder(Order $order, Request $request)
    {
        $user = User::find($request->user()->id);
        abort_if($order->user_id != $user->id, Response::HTTP_FORBIDDEN, '403 Forbidden');
        $order->load(['user', 'detail']);
        return new OrderResource($order);
    }
}

resources/views/admin/v2/category/child.blade.php
@foreach($items as $item)
    <tr style="margin-left: 10px">
        <td class="search-result-table-td">
            <label class="checkbox-parent">
                <input type="checkbox" class="checkbox-table cs1 ds{!! $item->id !!}"
                       onclick="checkInput('category','{!! $item->id !!}','.ds')">
                <span class="checkmark"></span>
            </label>
        </td>
        <td>{{$item->id}}</td>
        <td>{!! $prefix !!}{{$item->name}}</td>
        <td><img src="{{asset('/storage/categories/'.$item->banner)}}"
                 style="width: 200px;height: 200px"
                 alt="Main image 2"></td>
        <td>{{$item->sort}}</td>
        <td>
            <form
                action="{{route('update_category_visibility',['category'=>$item->id])}}"
                method="post">
                @csrf
                @method('PUT')
                @if($item->published)
                    <button class="btn btn-danger" style="background: green;color: white"
                            type="submit">Active
                    </button>
                @else
                    <button class="btn btn-success"
                            style="background: red;color: white" type="submit">Deactive
                    </button>
                @endif
            </form>
        </td>
        <td>{{$item->created_at}}</td>
        <td class="right-button-parent">
            <div class="right-buttons">
                <a href="{{route('category.edit',['category'=>$item->id])}}"
                   class="table-buttons">
                    <svg width="16" height="16" viewBox="0 0 16 16" fill="none"
                         xmlns="http://www.w3.org/2000/svg">
                        <g opacity="0.5">
                            <path
                                d="M1.06667 11.7333L0.713112 11.3797L0.566666 11.5262V11.7333H1.06667ZM10.6667 2.1333L11.0202 1.77975C10.9265 1.68598 10.7993 1.6333 10.6667 1.6333C10.5341 1.6333 10.4069 1.68598 10.3131 1.77975L10.6667 2.1333ZM13.8667 5.3333L14.2202 5.68685C14.4155 5.49159 14.4155 5.17501 14.2202 4.97975L13.8667 5.3333ZM4.26667 14.9333V15.4333H4.47377L4.62022 15.2869L4.26667 14.9333ZM1.06667 14.9333H0.566666C0.566666 15.2094 0.790523 15.4333 1.06667 15.4333V14.9333ZM1.42022 12.0869L11.0202 2.48685L10.3131 1.77975L0.713112 11.3797L1.42022 12.0869ZM10.3131 2.48685L13.5131 5.68685L14.2202 4.97975L11.0202 1.77975L10.3131 2.48685ZM13.5131 4.97975L3.91311 14.5797L4.62022 15.2869L14.2202 5.68685L13.5131 4.97975ZM4.26667 14.4333H1.06667V15.4333H4.26667V14.4333ZM1.56667 14.9333V11.7333H0.566666V14.9333H1.56667ZM9.06667 15.4333H15.9998V14.4333H9.06667V15.4333Z"
                                fill="#05061E"/>
                        </g>
                    </svg>
                </a>
                <button class="table-buttons"
                        onclick="opendeletePOPUP('{!! route('category.destroy',['category'=>$item->id]) !!}',{!! count($item->children) ? true:false !!})">
                    <svg width="16" height="16" viewBox="0 0 16 16" fill="none"
                         xmlns="http://www.w3.org/2000/svg">
                        <g opacity="0.5">
                            <path
                                d="M5.25714 3.32143V1.92857C5.25714 1.41574 5.66648 1 6.17143 1H9.82857C10.3335 1 10.7429 1.41574 10.7429 1.92857V3.32143M1 3.78571H15M3.37143 3.78571V13.0714C3.37143 13.5843 3.78077 14 4.28571 14H11.7143C12.2192 14 12.6286 13.5843 12.6286 13.0714V3.78571M8 6.62958V10.2277V11.4175"
                                stroke="#05061E"/>
                        </g>
                    </svg>
                </button>
            </div>
        </td>
    </tr>
    @if(count($item->children))
        @include('admin.v2.category.child',['items' => $item->children,'prefix'=>'&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;'.$prefix])
    @endif
@endforeach

resources/views/admin/v2/category/child_option.blade.php
@foreach($items as $item)
    <option value="{{$item->id}}">{!! $prefix.$item->name !!}</option>
    @if(count($item->children2))
        @include('admin.v2.category.child_option',['items' => $item->children2,'prefix'=>'&nbsp;&nbsp;'.$prefix])
    @endif
@endforeach

resources/views/admin/v2/category/child_option_edit.blade.php
@foreach($items as $item)
    <option value="{{$item->id}}" @if($item->id == $cat->parent_id) selected @endif>{!! $prefix.$item->name !!}</option>
    @if(count($item->children2))
        @include('admin.v2.category.child_option_edit',['items' => $item->children2,'prefix'=>'&nbsp;&nbsp;'.$prefix])
    @endif
@endforeach

resources/views/admin/v2/category/create.blade.php
@extends('layouts.v2.admin')

@section('breadcrump')
    <div class="top-section b-black">
        <div class="container">
            <div class="top-section-inner">
                <div>
                    <div class="page-links">
                        <a class="c-white-op-75 f-size-14">Ana səhifə > </a>
                        <a href="{{route('category.index')}}" class="c-white-op-75 f-size-14">&emsp14;Menu</a>
                        <span class="c-white-op-50 f-size-14">
                                Yenisini əlavə et
                            </span>
                    </div>
                    <h6 class="f-size-24 c-white">
                        Yenisini əlavə et
                    </h6>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('content')
    <div class="add-product-page b-white-1">
        <div class="container">
            @if($errors->any())
                {{dd($errors->all())}}
                <div style="background: red;color: white;font-size: 12px;border-radius: 4%" id="roles_create_error">
                    <ul style="margin-left: 5px;">
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            @if(session()->has('danger'))
                <h3 style="background: red;color:white">{{session()->get('danger')}}</h3>
            @endisset
            <form action="{{route('category.store')}}" method="post" enctype="multipart/form-data">
                @csrf
                <div class="row">
                    <div class="xl-2">
                    </div>
                    <div class="xl-9">
                        <div class="new-address-content bradius-8 b-white">
                            <div class="new-address-content-header bor-bottom-black-1">
                                <span class="f-size-16">
                                    Category Elave et
                                </span>
                            </div>
                            <div class="new-address-content-body">
                                <div class="new-address-content-input-groups">
                                    <div class="news-address-content-inputs">
                                        <label for="" class="f-size-14-b c-dblack-op-75 mb-12">
                                            Parent Category
                                        </label>
                                        <select name="parent_id" class="input-class">
                                            <option value="">Select Category</option>
                                            @foreach($category as $item)
                                                <option value="{{$item->id}}">{!! $item->name !!}</option>
                                                @if(count($item->children2))
                                                    @include('admin.v2.category.child_option',['items' => $item->children2,'prefix'=>'&nbsp;&nbsp;'])
                                                @endif
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="new-address-content-input-groups">
                                    <div class="news-address-content-inputs">
                                        <label for="" class="f-size-14-b c-dblack-op-75 mb-12">
                                            Name
                                        </label>
                                        <input type="text" class="input-class" name="name"
                                               value="{{old('name')}}">
                                    </div>
                                </div>
                                <div class="new-address-content-input-groups">
                                    <div class="news-address-content-inputs">
                                        <label for="" class="f-size-14-b c-dblack-op-75 mb-12">
                                            Sort
                                        </label>
                                        <input type="number" class="input-class" name="sort" value="{{old('sort')}}">
                                    </div>
                                </div>
                                <div class="new-address-content-input-groups">
                                    <div class="news-address-content-inputs">
                                        <label for="" class="f-size-14-b c-dblack-op-75 mb-12">
                                            Meta Title
                                        </label>
                                        <input type="text" class="input-class" name="meta_title"
                                               value="{{old('meta_title')}}">
                                    </div>
                                </div>
                                <div class="new-address-content-input-groups">
                                    <div class="news-address-content-inputs">
                                        <label for="" class="f-size-14-b c-dblack-op-75 mb-12">
                                            Meta Description
                                        </label>
                                        <textarea name="meta_desc" cols="30"
                                                  rows="10">{!! old('meta_desc') !!}</textarea>
                                    </div>
                                </div>
                                <div class="new-address-content-input-groups">
                                    <div class="news-address-content-inputs">
                                        <label for="" class="f-size-14-b c-dblack-op-75 mb-12">
                                            Banner
                                        </label>
                                        <input type="file" class="input-class" name="banner">
                                    </div>
                                    <div class="news-address-content-inputs">
                                        <label for="" class="f-size-14-b c-dblack-op-75 mb-12">
                                            Status
                                        </label>
                                        <label for="b">
                                            <div class="private f-size-14-b c-dblack-75">
                                                <div class="checkboxes">
                                                    <div class="check">
                                                        <input type="checkbox" name="published" id="b">
                                                        <label for="b"></label>
                                                    </div>
                                                </div>
                                            </div>
                                        </label>
                                    </div>
                                </div>
                                <button type="submit" class="new-address-button">
                                    Yadda saxla
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection