routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\HomeController;
use App\Models\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// V2 Routes
Route::group(['prefix' => '/v2'], function () {
    Route::get('/', [App\Http\Controllers\V2\Auth\LoginController::class, 'login'])->name('login');
    Route::post('login', [App\Http\Controllers\V2\Auth\LoginController::class, 'loginUser'])->name('loginUser');

    Route::get('debugadminon', function () {
        \Debugbar::enable();
    });
    Route::get('debugadminoff', function () {
        \Debugbar::disable();
    });

//    Route::post('/forgot_password', [App\Http\Controllers\V2\Auth\LoginController::class, 'forgot_password'])->name('v2.admin.forgot_password.store');
//    Route::get('/forgot_password', [App\Http\Controllers\V2\Auth\LoginController::class, 'get_forgot_password'])->name('v2.admin.forgot_password');
//    Route::get('/resetpass', [App\Http\Controllers\V2\Auth\LoginController::class, 'refresh_password'])->name('v2.admin.reset_password');
//    Route::post('/resetpass', [App\Http\Controllers\V2\Auth\LoginController::class, 'refresh_password_post']);

    Route::group(['prefix' => '/admin', 'middleware' => ['auth', 'auth.admin']], function () {
        Route::group(['middleware' => 'checkRole:1'], function () {
            Route::post('/logout', [App\Http\Controllers\V2\Auth\LoginController::class, 'logout'])->name('v2.admin.logout');

            Route::get('/client_login/{user}', [App\Http\Controllers\V2\AdminController::class, 'client_login'])->name('client_login');
            Route::resource('users', App\Http\Controllers\V2\UserController::class);
            Route::resource('roles', App\Http\Controllers\V2\RoleController::class);

            Route::resource('smstemplates', App\Http\Controllers\V2\SMSTemplateController::class);
            Route::delete('/deleteall_sms_tem', [\App\Http\Controllers\V2\SMSTemplateController::class, 'destroyAllSelections'])->name('deleteall_sms_tem');
            Route::put('/update/sms_temp/status/{smstemplate}', [\App\Http\Controllers\V2\SMSTemplateController::class, 'updateVisible'])->name('update.sms_temp');
            Route::get('/send/sms/clients', [\App\Http\Controllers\V2\SMSTemplateController::class, 'smsSendToClient'])->name('send.sms.admin');
            Route::post('/send/sms/clients', [\App\Http\Controllers\V2\SMSTemplateController::class, 'smsSendToClientPost'])->name('send.sms.admin.post');

            Route::resource('emailtemplates', App\Http\Controllers\V2\EmailTemplateController::class);
            Route::delete('/deleteall_email_tem', [\App\Http\Controllers\V2\EmailTemplateController::class, 'destroyAllSelections'])->name('deleteall_email_tem');
            Route::put('/update/email_temp/status/{emailtemplate}', [\App\Http\Controllers\V2\EmailTemplateController::class, 'updateVisible'])->name('update.email_temp');

            Route::delete('/adminus_destroyAllSelections', [\App\Http\Controllers\V2\AdminPanelUsersController::class, 'destroyAllSelections'])->name('adminus.deleteSelections');
            Route::resource('admin_panel_users', App\Http\Controllers\V2\AdminPanelUsersController::class);
            Route::delete('/roles_destroyAllSelections', [\App\Http\Controllers\V2\RoleController::class, 'destroyAllSelections'])->name('roles.deleteSelections');
            Route::resource('mektublar', App\Http\Controllers\V2\MektublarController::class);
            Route::delete('/mektub_destroyAllSelections', [\App\Http\Controllers\V2\MektublarController::class, 'destroyAllSelections'])->name('mektub.deleteSelections');
            Route::resource('coupons', App\Http\Controllers\V2\CouponController::class);
            Route::delete('/coupons_destroyAllSelections', [\App\Http\Controllers\V2\CouponController::class, 'destroyAllSelections'])->name('coupons.deleteSelections');

            Route::resource('category', \App\Http\Controllers\V2\CategoryController::class)->except('show');
            Route::delete('/categories_destroyAllSelections', [\App\Http\Controllers\V2\CategoryController::class, 'destroyAllSelections'])->name('category.deleteSelections');
            Route::put('/categories/update_category_visibility/{category}', [\App\Http\Controllers\V2\CategoryController::class, 'update_category_visibility'])->name('update_category_visibility');

        });
        Route::group(['middleware' => 'checkRole:1|4|3'], function () { //Kuryer
            Route::get('orders', [App\Http\Controllers\V2\OrderController::class, 'index'])->name('orders');
            Route::get('orders/{orderId}/{type}/showDetail', [App\Http\Controllers\V2\OrderController::class, 'showDetail'])->name('orders.showDetail');
            Route::post('orders/detail/update', [App\Http\Controllers\V2\OrderController::class, 'updateOrderDetailStatus'])->name('orders.updateOrderDetailStatus');
            Route::delete('orders/{detailId}/detail', [App\Http\Controllers\V2\OrderController::class, 'deleteOrderDetail'])->name('orders.deleteOrderDetail');
            Route::post('/orders/stock', [App\Http\Controllers\V2\OrderController::class, 'updateStock'])->name('orders.stock');
        });
        Route::group(['middleware' => 'checkRole:1|5'], function () { // Kontent
            Route::resource('banners', App\Http\Controllers\V2\BannerController::class);
            Route::put('/banner/update_banner_visibility/{banner}', [\App\Http\Controllers\V2\BannerController::class, 'update_banner_visibility'])->name('update_banner_visibility');
            Route::delete('/banner/delete/{banner}', [\App\Http\Controllers\V2\BannerController::class, 'destroy'])->name('delete_banner');
            Route::resource('brands', App\Http\Controllers\V2\BrandController::class);
            Route::delete('/stories_destroyAllSelections', [\App\Http\Controllers\V2\StoryController::class, 'destroyAllSelections'])->name('story.deleteSelections');
            Route::delete('/color_destroyAllSelections', [\App\Http\Controllers\V2\ColorController::class, 'destroyAllSelections'])->name('color.deleteSelections');
            Route::resource('stories', App\Http\Controllers\V2\StoryController::class);
            Route::resource('colors', App\Http\Controllers\V2\ColorController::class);
        });
        Route::group(['middleware' => 'checkRole:1|4|5'], function () { // Kontent ve ANbar
            Route::resource('products', App\Http\Controllers\V2\ProductController::class);
            Route::get('/product/{product_id}/changeStatus', [App\Http\Controllers\V2\ProductController::class, 'productsStatus'])->name('products.status');
            Route::post('/product/removeProductFromCombine', [App\Http\Controllers\V2\ProductController::class, 'removeProductFromCombine'])->name('products.removeProductFromCombine');
        });
        Route::group(['middleware' => 'checkRole:1|4'], function () {  //ANbar
            Route::resource('refler', App\Http\Controllers\V2\ReflerController::class);
            Route::delete('/refler_destroyAllSelections', [\App\Http\Controllers\V2\ReflerController::class, 'destroyAllSelections'])->name('refler.deleteSelections');
        });
        Route::group(['middleware' => 'checkRole:1'], function () {  //Statistics
            Route::get('statistics', [App\Http\Controllers\V2\StatisticsController::class, 'index'])->name('statistics.index');
            Route::get('statistics/{type}', [App\Http\Controllers\V2\StatisticsController::class, 'getData'])->name('statistics.getData');
        });
//        Route::get('dashboard', [App\Http\Controllers\V2\AdminController::class, 'dashboard'])->name('dashboard');
    });
});


// V1 Routes

//Route::redirect('/', '/login');
Route::get('', [HomeController::class, 'index'])->name('main');
Route::get('/login', [LoginController::class, 'index'])->name('admin.login');
Route::post('/login', [LoginController::class, 'login']);

Route::prefix('admin')->middleware(['auth', 'auth.admin'])->name('admin.')->group(function () {
    Route::get('/', [AdminController::class, 'products'])->name('dashboard');
    Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
    Route::post('/logout', [LoginController::class, 'logout']);

    Route::post('/file/{type}', [AdminController::class, 'uploadFile'])->name('file.upload');
    Route::delete('/file/{id}', [AdminController::class, 'deleteFile'])->name('file.delete');

    Route::get('api/products', [AdminController::class, 'productsList']);
    Route::get('api/users', [AdminController::class, 'usersList']);

    Route::get('/products', [AdminController::class, 'products'])->name('products');
    Route::get('/products/create', [AdminController::class, 'productsCreate'])->name('products.create');
    Route::post('/products/create', [AdminController::class, 'productsStore'])->name('products.store');
    Route::get('/products/{product_id}', [AdminController::class, 'productsEdit'])->name('products.edit');
    Route::put('/products/{product_id}', [AdminController::class, 'productsUpdate'])->name('products.update');
    Route::post('/products/{product_id}', [AdminController::class, 'productsStatus'])->name('products.status');
    Route::delete('/products/{product_id}', [AdminController::class, 'productsDelete'])->name('products.delete');

    Route::get('/orders', [AdminController::class, 'orders'])->name('orders');
    Route::post('/orders', [AdminController::class, 'ordersStatus'])->name('orders.status');

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\UserContactInformationRequest;
use App\Http\Requests\UserUpdateSettingsRequest;
use App\Http\Resources\OrderCollection;
use App\Http\Resources\UserResource;
use App\Models\User;
use App\Traits\ApiResponser;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class UserController extends Controller
{
    use ApiResponser;

    /**
     * Get the authenticated User
     *
     * @return [json] user object
     */
    public function getUser(Request $request)
    {
        $user = User::find($request->user()->id);
        return new UserResource($user);
    }

    public function updateContactInformations(UserContactInformationRequest $request)
    {
        $user = User::find($request->user()->id);
        try {
            $user->name = $request->get('firstName') . ' ' . $request->get('lastName');
            $user->phone = $request->get('phone');
            $user->city = $request->get('city');
            $user->address = $request->get('address');
            $user->save();
            return new UserResource($user);
        } catch (\Exception $e) {
            return $this->sendError(null, $e->getMessage(), 500);
        }
    }

    public function updateSettings(UserUpdateSettingsRequest $request)
    {
        try {
            $request->user()->fill([
                'name' => $request->input('firstname') . ' ' . $request->input('lastname'),
                'email' => $request->get('email'),
            ])->save();
            if ($request->get('password')) {
                $request->user()->fill([
                    'password' => Hash::make($request->get('password')),
                ])->save();
            }
            return new UserResource($request->user());
        } catch (\Exception $e) {
            return $this->sendError(null, $e->getMessage(), 500);
        }
    }

    public function getOrders(Request $request)
    {
        $limit = 5;
        $user = User::find($request->user()->id);
        return new OrderCollection($user->orders()->orderBy('created_at', 'desc')->with(['detail'])->paginate($limit));
    }
}

app/Http/Controllers/V2/AdminController.php
<?php

namespace App\Http\Controllers\V2;

use App\Http\Controllers\Controller;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Support\Facades\Redirect;

class AdminController extends Controller
{
    private $pac = "Modabu Personal Access Client";

    public function dashboard()
    {
        return view('admin.v2.dashboard');
    }

    public function client_login(User $user)
    {
        $tokenResult = $user->createToken($this->pac);

        return Redirect::to('https://modabu.az/?token_client_access=' . $tokenResult->accessToken);
    }
}

app/Http/Controllers/V2/AdminPanelUsersController.php
<?php

namespace App\Http\Controllers\V2;

use App\Http\Controllers\Controller;
use App\Models\Role;
use App\Models\RoleUser;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Pipeline\Pipeline;
use Illuminate\Support\Facades\Hash;

class AdminPanelUsersController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $users = User::query()->has('roles')
            ->orderBy('created_at', 'desc');

        if ($request->has('role')) {
            if ($request->role) {
                $users = User::query()->orderBy('created_at', 'desc');
            }
        }
        $user = $users->with('roles');

        $users = app(Pipeline::class)
            ->send($users)
            ->through([
                \App\QueryFilters\Name::class,
                \App\QueryFilters\Role::class,
            ])
            ->thenReturn()
            ->paginate(getPaginationLimit());

        $roles = Role::select([
            'id', 'title'
        ])->get();

        return view('admin.v2.adminpanel_users.index', compact('users', 'roles'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param User $user
     * @return \Illuminate\Http\Response
     */
    public function store(\App\Http\Requests\V2\AdminPanelUserRequest $request, User $user, RoleUser $roleUser)
    {
        $data = $request->except('_token');
        $data['password'] = Hash::make($data['password']);
        $user->fill($data);
        $user->save();
        $roleUser->insert([
            'role_id' => $data['roles'],
            'user_id' => $user->id
        ]);
        return redirect(route('admin_panel_users.index'))->with('success', 'Əməliyyat uğurla Insert Oldu.');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param User $admin_panel_user
     * @return \Illuminate\Http\Response
     */
    public function update(\App\Http\Requests\V2\AdminPanelUserRequest $request, User $admin_panel_user)
    {
        $data = $request->except('_token');
        if ($data['password']) {
            $data['password'] = Hash::make($data['password']);
        } else {
            $data['password'] = $admin_panel_user->password;
        }
        if ($data['roles']) {
            RoleUser::where('user_id', $admin_panel_user->id)->update([
                'role_id' => $data['roles']
            ]);
        }
        if (!$data['phone']) {
            $data['phone'] = $admin_panel_user->phone;
        }
        $admin_panel_user->fill($data);
        $admin_panel_user->save();
        return redirect(route('admin_panel_users.index'))->with('success', 'Əməliyyat uğurla Update Oldu.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $admin_panel_user)
    {
        RoleUser::where('user_id', $admin_panel_user->id)->delete();
        User::where('id', $admin_panel_user)->delete();
        return response()->json(['message' => 'Silinme uğurla tamamlandı.'], 200);
    }

    public function destroyAllSelections(Request $request)
    {
        $request->validate(['keys' => 'present']);
        if ($request->keys) {
            $array = explode(',', $request->keys);
            RoleUser::whereIn('user_id', $array)->delete();
            User::whereIn('id', $array)->delete();
        }
        return response()->json(['message' => 'Əməliyyat uğurla tamamlandı.'], 200);
    }
}

app/Http/Controllers/V2/Api/ApiController.php
<?php

namespace App\Http\Controllers\V2\Api;

use App\Http\Controllers\Controller;
use App\Models\City;
use App\Traits\ApiResponser;
use Illuminate\Http\Request;

class ApiController extends Controller
{
    use ApiResponser;
    public function cities()
    {
        return $this->sendResponse(City::all(), '');
    }
}

resources/views/admin/v2/users/create.blade.php
@extends('layouts.v2.admin')

@section('body_class','add-product')

@section('breadcrump')
    <div class="top-section b-black">
        <div class="container">
            <div class="top-section-inner">
                <div>
                    <div class="page-links">
                        <a class="c-white-op-75 f-size-14">Ana səhifə > </a>
                        <a href="{{route('users.index')}}" class="c-white-op-75 f-size-14">&emsp14;İstifadəçilər</a>
                        <span class="c-white-op-50 f-size-14">
                                Yenisini əlavə et
                            </span>
                    </div>
                    <h6 class="f-size-24 c-white">
                        Yenisini əlavə et
                    </h6>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('content')
    <div class="add-product-page b-white-1">
        <div class="container">
            <form action="{{route('users.store')}}" method="post">
                @csrf
                <div class="row">
                    <div class="xl-3">
                        <div class="new-address bradius-8 b-white">
                            <div class="new-address-header bor-bottom-black-1">
                                <h4 class="f-size-20">
                                    Yenisini əlavə et
                                </h4>
                                <button>
                                    <svg width="16" height="16" viewBox="0 0 16 16" fill="none" xmlns="http://www.w3.org/2000/svg">
                                        <path d="M1.59998 1.60001L14.4 14.4M1.59998 14.4L14.4 1.60001" stroke="#0B0B18" stroke-width="2"></path>
                                    </svg>
                                </button>
                            </div>
                            <ul class="new-address-body">
                                <li>
                                    <a href="" class="f-size-14-b c-dblack-75 active">
                                        Haqqında
                                    </a>
                                </li>
                                <li>
                                    <a href="" class="f-size-14-b c-dblack-75">
                                        Sifariş
                                    </a>
                                </li>
                                <li>
                                    <a href="" class="f-size-14-b c-dblack-75">
                                        Teqlər
                                    </a>
                                </li>
                                <li>
                                    <a href="" class="f-size-14-b c-dblack-75">
                                        SEO
                                    </a>
                                </li>
                            </ul>
                        </div>
                    </div>
                    <div class="xl-9">
                        <div class="new-address-content bradius-8 b-white">
                            <div class="new-address-content-header bor-bottom-black-1">
                                <span class="f-size-16">
                                    Haqqında
                                </span>
                            </div>
                            <div class="new-address-content-body">
                                <div class="new-address-content-input-groups">
                                    <div class="news-address-content-inputs">
                                        <label for="" class="f-size-14-b c-dblack-op-75 mb-12">
                                            Ad
                                        </label>
                                        <input type="text" class="input-class" name="name">
                                    </div>
                                    <div class="news-address-content-inputs">
                                        <label for="" class="f-size-14-b c-dblack-op-75 mb-12">
                                            Soyad
                                        </label>
                                        <input type="text" class="input-class" name="surname">
                                    </div>
                                </div>
                                <div class="new-address-content-input-groups">
                                    <div class="news-address-content-inputs">
                                        <label for="" class="f-size-14-b c-dblack-op-75 mb-12">
                                            Email
                                        </label>
                                        <input type="email" name="email" class="input-class" >
                                    </div>
                                    <div class="news-address-content-inputs">
                                        <label for="" class="f-size-14-b c-dblack-op-75 mb-12">
                                            Mobil nömrə
                                        </label>
                                        <div class="mobile-select">
                                            <div class="selectHolder selectThin mobile-op">
                                                <select name="phone_prefix" id="">
                                                    <option value="050">050</option>
                                                    <option value="051">051</option>
                                                    <option value="055">055</option>
                                                    <option value="070">070</option>
                                                    <option value="077">077</option>
                                                    <option value="099">099</option>
                                                </select>
                                            </div>
                                            <input type="number" name="phone" class="input-class">
                                        </div>
                                    </div>
                                </div>
                                <div class="new-address-content-input-groups">
                                    <div class="news-address-content-inputs">
                                        <label for="" class="f-size-14-b c-dblack-op-75 mb-12">
                                            Şifrə
                                        </label>
                                        <input type="password" class="input-class" name="password">
                                    </div>
                                    <div class="news-address-content-inputs">
                                        <label for="" class="f-size-14-b c-dblack-op-75 mb-12">
                                            Status
                                        </label>
                                        <label for="b">
                                            <div class="private f-size-14-b c-dblack-75">
                                                Aktivdir
                                                <div class="checkboxes">
                                                    <div class="check">
                                                        <input type="checkbox" name="status" checked="" id="b">
                                                        <label for="b"></label>
                                                    </div>
                                                </div>
                                            </div>
                                        </label>
                                    </div>
                                </div>
                                <button type="submit" class="new-address-button">
                                    Yadda saxla
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection