routes/web.php
<?php

use App\Http\Controllers\AdminController;
use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\HomeController;
use App\Models\Order;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

// V2 Routes
Route::group(['prefix' => '/v2'], function () {
    Route::get('/', [App\Http\Controllers\V2\Auth\LoginController::class, 'login'])->name('login');
    Route::post('login', [App\Http\Controllers\V2\Auth\LoginController::class, 'loginUser'])->name('loginUser');

    Route::get('debugadminon', function () {
        \Debugbar::enable();
    });
    Route::get('debugadminoff', function () {
        \Debugbar::disable();
    });

//    Route::post('/forgot_password', [App\Http\Controllers\V2\Auth\LoginController::class, 'forgot_password'])->name('v2.admin.forgot_password.store');
//    Route::get('/forgot_password', [App\Http\Controllers\V2\Auth\LoginController::class, 'get_forgot_password'])->name('v2.admin.forgot_password');
//    Route::get('/resetpass', [App\Http\Controllers\V2\Auth\LoginController::class, 'refresh_password'])->name('v2.admin.reset_password');
//    Route::post('/resetpass', [App\Http\Controllers\V2\Auth\LoginController::class, 'refresh_password_post']);

    Route::group(['prefix' => '/admin', 'middleware' => ['auth', 'auth.admin']], function () {
        Route::group(['middleware' => 'checkRole:1'], function () {
            Route::post('/logout', [App\Http\Controllers\V2\Auth\LoginController::class, 'logout'])->name('v2.admin.logout');

            Route::get('/client_login/{user}', [App\Http\Controllers\V2\AdminController::class, 'client_login'])->name('client_login');
            Route::resource('users', App\Http\Controllers\V2\UserController::class);
            Route::resource('roles', App\Http\Controllers\V2\RoleController::class);

            Route::resource('smstemplates', App\Http\Controllers\V2\SMSTemplateController::class);
            Route::delete('/deleteall_sms_tem', [\App\Http\Controllers\V2\SMSTemplateController::class, 'destroyAllSelections'])->name('deleteall_sms_tem');
            Route::put('/update/sms_temp/status/{smstemplate}', [\App\Http\Controllers\V2\SMSTemplateController::class, 'updateVisible'])->name('update.sms_temp');
            Route::get('/send/sms/clients', [\App\Http\Controllers\V2\SMSTemplateController::class, 'smsSendToClient'])->name('send.sms.admin');
            Route::post('/send/sms/clients', [\App\Http\Controllers\V2\SMSTemplateController::class, 'smsSendToClientPost'])->name('send.sms.admin.post');

            Route::resource('emailtemplates', App\Http\Controllers\V2\EmailTemplateController::class);
            Route::delete('/deleteall_email_tem', [\App\Http\Controllers\V2\EmailTemplateController::class, 'destroyAllSelections'])->name('deleteall_email_tem');
            Route::put('/update/email_temp/status/{emailtemplate}', [\App\Http\Controllers\V2\EmailTemplateController::class, 'updateVisible'])->name('update.email_temp');

            Route::delete('/adminus_destroyAllSelections', [\App\Http\Controllers\V2\AdminPanelUsersController::class, 'destroyAllSelections'])->name('adminus.deleteSelections');
            Route::resource('admin_panel_users', App\Http\Controllers\V2\AdminPanelUsersController::class);
            Route::delete('/roles_destroyAllSelections', [\App\Http\Controllers\V2\RoleController::class, 'destroyAllSelections'])->name('roles.deleteSelections');
            Route::resource('mektublar', App\Http\Controllers\V2\MektublarController::class);
            Route::delete('/mektub_destroyAllSelections', [\App\Http\Controllers\V2\MektublarController::class, 'destroyAllSelections'])->name('mektub.deleteSelections');
            Route::resource('coupons', App\Http\Controllers\V2\CouponController::class);
            Route::delete('/coupons_destroyAllSelections', [\App\Http\Controllers\V2\CouponController::class, 'destroyAllSelections'])->name('coupons.deleteSelections');

            Route::resource('category', \App\Http\Controllers\V2\CategoryController::class)->except('show');
            Route::delete('/categories_destroyAllSelections', [\App\Http\Controllers\V2\CategoryController::class, 'destroyAllSelections'])->name('category.deleteSelections');
            Route::put('/categories/update_category_visibility/{category}', [\App\Http\Controllers\V2\CategoryController::class, 'update_category_visibility'])->name('update_category_visibility');

        });
        Route::group(['middleware' => 'checkRole:1|4|3'], function () { //Kuryer
            Route::get('orders', [App\Http\Controllers\V2\OrderController::class, 'index'])->name('orders');
            Route::get('orders/{orderId}/{type}/showDetail', [App\Http\Controllers\V2\OrderController::class, 'showDetail'])->name('orders.showDetail');
            Route::post('orders/detail/update', [App\Http\Controllers\V2\OrderController::class, 'updateOrderDetailStatus'])->name('orders.updateOrderDetailStatus');
            Route::delete('orders/{detailId}/detail', [App\Http\Controllers\V2\OrderController::class, 'deleteOrderDetail'])->name('orders.deleteOrderDetail');
            Route::post('/orders/stock', [App\Http\Controllers\V2\OrderController::class, 'updateStock'])->name('orders.stock');
        });
        Route::group(['middleware' => 'checkRole:1|5'], function () { // Kontent
            Route::resource('banners', App\Http\Controllers\V2\BannerController::class);
            Route::put('/banner/update_banner_visibility/{banner}', [\App\Http\Controllers\V2\BannerController::class, 'update_banner_visibility'])->name('update_banner_visibility');
            Route::delete('/banner/delete/{banner}', [\App\Http\Controllers\V2\BannerController::class, 'destroy'])->name('delete_banner');
            Route::resource('brands', App\Http\Controllers\V2\BrandController::class);
            Route::delete('/stories_destroyAllSelections', [\App\Http\Controllers\V2\StoryController::class, 'destroyAllSelections'])->name('story.deleteSelections');
            Route::delete('/color_destroyAllSelections', [\App\Http\Controllers\V2\ColorController::class, 'destroyAllSelections'])->name('color.deleteSelections');
            Route::resource('stories', App\Http\Controllers\V2\StoryController::class);
            Route::resource('colors', App\Http\Controllers\V2\ColorController::class);
        });
        Route::group(['middleware' => 'checkRole:1|4|5'], function () { // Kontent ve ANbar
            Route::resource('products', App\Http\Controllers\V2\ProductController::class);
            Route::get('/product/{product_id}/changeStatus', [App\Http\Controllers\V2\ProductController::class, 'productsStatus'])->name('products.status');
            Route::post('/product/removeProductFromCombine', [App\Http\Controllers\V2\ProductController::class, 'removeProductFromCombine'])->name('products.removeProductFromCombine');
        });
        Route::group(['middleware' => 'checkRole:1|4'], function () {  //ANbar
            Route::resource('refler', App\Http\Controllers\V2\ReflerController::class);
            Route::delete('/refler_destroyAllSelections', [\App\Http\Controllers\V2\ReflerController::class, 'destroyAllSelections'])->name('refler.deleteSelections');
        });
        Route::group(['middleware' => 'checkRole:1'], function () {  //Statistics
            Route::get('statistics', [App\Http\Controllers\V2\StatisticsController::class, 'index'])->name('statistics.index');
            Route::get('statistics/{type}', [App\Http\Controllers\V2\StatisticsController::class, 'getData'])->name('statistics.getData');
        });
//        Route::get('dashboard', [App\Http\Controllers\V2\AdminController::class, 'dashboard'])->name('dashboard');
    });
});


// V1 Routes

//Route::redirect('/', '/login');
Route::get('', [HomeController::class, 'index'])->name('main');
Route::get('/login', [LoginController::class, 'index'])->name('admin.login');
Route::post('/login', [LoginController::class, 'login']);

Route::prefix('admin')->middleware(['auth', 'auth.admin'])->name('admin.')->group(function () {
    Route::get('/', [AdminController::class, 'products'])->name('dashboard');
    Route::get('/logout', [LoginController::class, 'logout'])->name('logout');
    Route::post('/logout', [LoginController::class, 'logout']);

    Route::post('/file/{type}', [AdminController::class, 'uploadFile'])->name('file.upload');
    Route::delete('/file/{id}', [AdminController::class, 'deleteFile'])->name('file.delete');

    Route::get('api/products', [AdminController::class, 'productsList']);
    Route::get('api/users', [AdminController::class, 'usersList']);

    Route::get('/products', [AdminController::class, 'products'])->name('products');
    Route::get('/products/create', [AdminController::class, 'productsCreate'])->name('products.create');
    Route::post('/products/create', [AdminController::class, 'productsStore'])->name('products.store');
    Route::get('/products/{product_id}', [AdminController::class, 'productsEdit'])->name('products.edit');
    Route::put('/products/{product_id}', [AdminController::class, 'productsUpdate'])->name('products.update');
    Route::post('/products/{product_id}', [AdminController::class, 'productsStatus'])->name('products.status');
    Route::delete('/products/{product_id}', [AdminController::class, 'productsDelete'])->name('products.delete');

    Route::get('/orders', [AdminController::class, 'orders'])->name('orders');
    Route::post('/orders', [AdminController::class, 'ordersStatus'])->name('orders.status');

resources/views/admin/partials/footer.blade.php
<!--begin::Footer-->
<div class="footer bg-white py-4 d-flex flex-lg-column" id="kt_footer">

    <!--begin::Container-->
    <div class="container d-flex flex-column flex-md-row align-items-center justify-content-between">

        <!--begin::Copyright-->
        <div class="text-dark order-2 order-md-1">
            <span class="text-muted font-weight-bold mr-2">2020 ©</span>
            <a href="{{route('admin.dashboard')}}" target="_blank" class="text-dark-75 text-hover-primary">Modabu</a>
        </div>

        <!--end::Copyright-->

        <!--begin::Nav-->
        <!-- <div class="nav nav-dark order-1 order-md-2">
            <a href="http://keenthemes.com/metronic" target="_blank" class="nav-link pr-3 pl-0">About</a>
            <a href="http://keenthemes.com/metronic" target="_blank" class="nav-link px-3">Team</a>
            <a href="http://keenthemes.com/metronic" target="_blank" class="nav-link pl-3 pr-0">Contact</a>
        </div> -->

        <!--end::Nav-->
    </div>

    <!--end::Container-->
</div>

<!--end::Footer-->

resources/views/admin/partials/header-mobile.blade.php
<!--begin::Header Mobile-->
<div id="kt_header_mobile" class="header-mobile">

    <!--begin::Logo-->
    <a href="{{route('admin.dashboard')}}">
        <img alt="Logo" src="{{asset('/files/front/assets/svg/logo.svg')}}" class="logo-default max-h-30px"/>
    </a>

    <!--end::Logo-->

    <!--begin::Toolbar-->
    <div class="d-flex align-items-center">
        <button class="btn p-0 burger-icon burger-icon-left ml-4" id="kt_header_mobile_toggle">
            <span></span>
        </button>
        <button class="btn btn-icon btn-hover-transparent-white p-0 ml-3" id="kt_header_mobile_topbar_toggle">
					<span class="svg-icon svg-icon-xl">

						<!--begin::Svg Icon | path:assets/media/svg/icons/General/User.svg-->
						<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="24px"
                             height="24px" viewBox="0 0 24 24" version="1.1">
							<g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
								<polygon points="0 0 24 0 24 24 0 24"/>
								<path
                                    d="M12,11 C9.790861,11 8,9.209139 8,7 C8,4.790861 9.790861,3 12,3 C14.209139,3 16,4.790861 16,7 C16,9.209139 14.209139,11 12,11 Z"
                                    fill="#000000" fill-rule="nonzero" opacity="0.3"/>
								<path
                                    d="M3.00065168,20.1992055 C3.38825852,15.4265159 7.26191235,13 11.9833413,13 C16.7712164,13 20.7048837,15.2931929 20.9979143,20.2 C21.0095879,20.3954741 20.9979143,21 20.2466999,21 C16.541124,21 11.0347247,21 3.72750223,21 C3.47671215,21 2.97953825,20.45918 3.00065168,20.1992055 Z"
                                    fill="#000000" fill-rule="nonzero"/>
							</g>
						</svg>
                        <!--end::Svg Icon-->
					</span>
        </button>
    </div>
    <!--end::Toolbar-->
</div>
<!--end::Header Mobile-->

resources/views/admin/partials/header.blade.php
<!--begin::Header-->
<div id="kt_header" class="header header-fixed">

    <!--begin::Container-->
    <div class="container-fluid d-flex align-items-stretch justify-content-between">

        <!--begin::Left-->
        <div class="d-flex align-items-stretch mr-3">

            <!--begin::Header Logo-->
            <div class="header-logo">
                <a href="{{ route('admin.dashboard') }}">
                    <img alt="Modabu Logo" width="120px" src="{{asset("assets/media/logo2.svg")}}" class="logo-default max-h-40px" />
                    <img alt="Logo" src="{{asset("assets/media/logo2.svg")}}" class="logo-sticky max-h-40px" />
                </a>
            </div>

            <!--end::Header Logo-->

            <!--begin::Header Menu Wrapper-->
            <div class="header-menu-wrapper header-menu-wrapper-left" id="kt_header_menu_wrapper">

                <!--begin::Header Menu-->
                <div id="kt_header_menu"
                    class="header-menu header-menu-left header-menu-mobile header-menu-layout-default">

                    <!--begin::Header Nav-->
                    <ul class="menu-nav">
                        <!-- <li class="menu-item menu-item-open menu-item-here menu-item-submenu menu-item-rel menu-item-open menu-item-here"
                            data-menu-toggle="click" aria-haspopup="true">
                            <a href="index.php" class="menu-link">
                                <span class="menu-text">Əsas</span>
                                <i class="menu-arrow"></i>
                            </a>
                        </li> -->
                        <li class="menu-item  menu-item-submenu">
                            <a href="{{ route('admin.users') }}" class="menu-link">
                                <span class="svg-icon menu-icon"></span>
                                <span class="menu-text">İstifadəçilər</span>
                            </a>
                        </li>
                        <li class="menu-item  menu-item-submenu">
                            <a href="{{ route('admin.orders') }}" class="menu-link">
                                <span class="svg-icon menu-icon"></span>
                                <span class="menu-text">Sifarişlər</span>
                            </a>
                        </li>
                        <li class="menu-item  menu-item-submenu">
                            <a href="{{ route('admin.products') }}" class="menu-link">
                                <span class="svg-icon menu-icon"></span>
                                <span class="menu-text">Məhsullar</span>
                            </a>
                        </li>
                        <li class="menu-item  menu-item-submenu">
                            <a href="{{ route('admin.banners') }}" class="menu-link">
                                <span class="svg-icon menu-icon"></span>
                                <span class="menu-text">Bannerlər</span>
                            </a>
                        </li>
                        <li class="menu-item  menu-item-submenu">
                            <a href="{{ route('admin.products') }}" class="menu-link">
                                <span class="svg-icon menu-icon"></span>
                                <span class="menu-text">Kateqoriyalar</span>
                            </a>
                        </li>

                        {{-- <li class="menu-item  menu-item-submenu menu-item-rel" data-menu-toggle="click"
                            aria-haspopup="true">
                            <a href="javascript:;" class="menu-link menu-toggle">
                                <span class="menu-text">Blog</span>
                                <span class="menu-desc"></span>
                                <i class="menu-arrow"></i>
                            </a>
                            <div class="menu-submenu menu-submenu-classic menu-submenu-left">
                                <ul class="menu-subnav">
                                    <li class="menu-item  menu-item-submenu">
                                        <a href="{{ route('admin.products') }}" class="menu-link">
                                            <span class="svg-icon menu-icon"></span>
                                            <span class="menu-text">Categories</span>
                                        </a>
                                    </li>
                                    <li class="menu-item  menu-item-submenu">
                                        <a href="{{ route('admin.products') }}" class="menu-link">
                                            <span class="svg-icon menu-icon"></span>
                                            <span class="menu-text">Blogs</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </li> --}}

                        <li class="menu-item  menu-item-submenu">
                            <a href="{{ route('admin.products') }}" class="menu-link">
                                <span class="svg-icon menu-icon"></span>
                                <span class="menu-text">Əlaqə</span>
                            </a>
                        </li>
                        <li class="menu-item  menu-item-submenu">
                            <a href="{{ route('admin.products') }}" class="menu-link">
                                <span class="svg-icon menu-icon"></span>
                                <span class="menu-text">Tənzimləmələr</span>
                            </a>
                        </li>
                        {{-- 
                        <li class="menu-item  menu-item-submenu">
                            <a href="?page=categories" class="menu-link">
                                <span class="svg-icon menu-icon"></span>
                                <span class="menu-text">Categories</span>
                            </a>
                        </li>
                         --}}
                    </ul>
                </div>
            </div>
        </div>

        <!--end::Left-->

        <!--begin::Topbar-->
        <div class="topbar">
            <!--begin::User-->
            <div class="dropdown">

                <!--begin::Toggle-->
                <div class="topbar-item ">
                    <div class="btn btn-icon btn-hover-transparent-white d-flex align-items-center btn-lg px-md-2 w-md-auto"
                        id="kt_quick_user_toggle">
                        <span
                            class="text-white opacity-70 font-weight-bold font-size-base d-none d-md-inline mr-1">Salam,</span>
                        <span
                            class="text-white opacity-90 font-weight-bolder font-size-base d-none d-md-inline mr-4">{{ auth()->user()->name }}</span>
                        <span class="symbol symbol-35">
                            <span class="symbol-label text-white font-size-h5 font-weight-bold bg-white-o-30">{{ substr(auth()->user()->name, 0, 1) }}</span>
                        </span>
                    </div>
                </div>

                <!--end::Toggle-->
            </div>

            <!--end::User-->
        </div>

        <!--end::Topbar-->
    </div>

    <!--end::Container-->
</div>

<!--end::Header-->

resources/views/admin/partials/layout.blade.php
<!--begin::Main-->

@include("admin.partials.header-mobile")
<div class="d-flex flex-column flex-root">

    <!--begin::Page-->
    <div class="d-flex flex-row flex-column-fluid page">

        <!--begin::Wrapper-->
        <div class="d-flex flex-column flex-row-fluid wrapper" id="kt_wrapper">

        @include("admin.partials.header")

        <!--begin::Content-->
            <div class="content d-flex flex-column flex-column-fluid" id="kt_content">


                @include("admin.partials.subheader")

                @yield("content")

            </div>

            <!--end::Content-->

            @include("admin.partials.footer")
        </div>

        <!--end::Wrapper-->
    </div>

    <!--end::Page-->
</div>

<!--end::Main-->

resources/views/admin/partials/subheader.blade.php
<!--begin::Subheader-->
<div class="subheader py-2 py-lg-12 subheader-transparent" id="kt_subheader">
    <div class="container d-flex align-items-center justify-content-between flex-wrap flex-sm-nowrap">

        <!--begin::Info-->
        <div class="d-flex align-items-center flex-wrap mr-1">

            <!--begin::Heading-->
            <div class="d-flex flex-column">

                <!--begin::Title-->
                <h2 class="text-white font-weight-bold my-2 mr-5">
                    {{$page_title}}
                </h2>

                <!--end::Title-->


                <!--begin::Breadcrumb-->
                <div class="d-flex align-items-center font-weight-bold my-2">
                    <!--begin::Item-->
                    <a href="#" class="opacity-75 hover-opacity-100">
                        <i class="flaticon2-shelter text-white icon-1x"></i>
                    </a>
                    <!--end::Item-->
                    <!--begin::Item-->
                    <span class="label label-dot label-sm bg-white opacity-75 mx-3"></span>
                    <a href="index.php" class="text-white text-hover-white opacity-75 hover-opacity-100">
                        Modabu </a>
                    <!--end::Item-->
                    <!--begin::Item-->
                    <span class="label label-dot label-sm bg-white opacity-75 mx-3"></span>
                    <a href="" class="text-white text-hover-white opacity-75 hover-opacity-100">
                        {{$page_breadcrumb}}
                    </a>
                    <!--end::Item-->
                    <span class="label label-dot label-sm bg-white opacity-75 mx-3"></span>
                    <a href="" class="text-white text-hover-white opacity-75 hover-opacity-100">
{{--                        {{$reysNumber}}--}}
                    </a>
                    <!--end::Item-->
                </div>
                <!--end::Breadcrumb-->
            </div>

            <!--end::Heading-->
        </div>

        <!--end::Info-->


    </div>
</div>

<!--end::Subheader-->